
server:
  port: 8080
  servlet:
    context-path: /product-service

spring:
  datasource:
    url: jdbc:mysql://mysql-product:3306/product_db?serverTimezone=Europe/Berlin
    username: product_user
    password: product_user
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: kafka:9092

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gwatcho-shop
          jwk-set-uri: http://keycloak:8080/realms/gwatcho-shop/protocol/openid-connect/certs
