server:
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: /product-service

spring:
  application:
    name: product-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 10

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:product-service}
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.gwatcho.productservice.event
        spring.json.value.default.type: com.gwatcho.productservice.event.ProductStockRequestedEvent
        spring.json.use.type.headers: false


  datasource:
    url: jdbc:mysql://localhost:3306/test_product_db?createDatabaseIfNotExist=true&serverTimezone=Europe/Berlin
    username: root
    password: root4Web!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

app:
  kafka:
    consumer:
      group-id: product-service

    topics:
      product-stock-requested: product.stock.requested

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.orm.jdbc.extract: OFF

management:
  endpoints:
    web:
      exposure:
        include: health,info


outbox:
  publisher:
    fixed-delay: 5000
    batch-size: 100
    max-retries: 5